name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 4.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false \
              -var "vm_admin_username=${{ secrets.VM_USERNAME }}" \
              -var "vm_admin_password=${{ secrets.VM_PASSWORD }}"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve \
              -var "vm_admin_username=${{ secrets.VM_USERNAME }}" \
              -var "vm_admin_password=${{ secrets.VM_PASSWORD }}"
